### ISSUE TITLE
No delegateCommandHandler for vscode.java.test.search.items

### ISSUE THREAD

**Issue by lapidcj** [microsoft/vscode-java-test#1062]
I got this problem for weeks. 
I can not find the 'Run Test/ Debug Test' above my test method. I checked my .classpath and the code `<attribute name="test" value="true"/>` exists. I have tried restarting and reloading vscode, also reinstall the `Debugger for Java` and `Java Test Runner` extension, but it doesn't work.
Has anyone meet the same issues? How did you solve it?

**Comment by jdneo** [comment]
Does your jdk version below 11?

**Comment by lapidcj** [comment]
Yes,but my Language Support for Java(TM) by Red Hat version is v0.64.1, I didn't upgrade it because my company use jdk1.8

**Comment by jdneo** [comment]
I see. Recently we update the requirement of Test Runner to JDK 11 as well, so that's the reason.

Well, if you are not working with an old gradle project, you can still use JDK 8 to build your project as well as use the latest bits of VS Code Java, see: https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692

I strongly recommend to stay with the newest version to enjoy the bunch of improvements there. :)

**Comment by lapidcj** [comment]
Thanks, I degrade the version of Java Test Runner extension, and it works. VS code is a very good editor.

**Comment by jdneo** [comment]
Again, downgrade the extension is just a workaround. If your workload allows you to install two versions of JDK. I strongly recommend you to give it a try.

**Comment by zypA13510** [comment]
I'm having this issue even if my Test Runner extension stayed at 0.24.2 due to old VSCode version. I checked the README, 0.24.2 should require JDK 8 only. Any idea why?

**Comment by jdneo** [comment]
@zypA13510 Can you update the VS Code and all the Java extensions to the latest and try again?

If you want to stay at JDK 8 for your project, you can add the setting mentioned in this issue: https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692
