### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode-java-test#1164]
high CPU usage was reported here https://github.com/redhat-developer/vscode-java/issues/851

based on the discussions, it seems that it is coming from VS Code Java Test.
I think this comment https://github.com/redhat-developer/vscode-java/issues/851#issuecomment-596522231 is the one providing the more information.

**Comment by jdneo** [comment]
So, we also noticed the performance issues. In order to solve them, several efforts are made including but not limited to：

- Use `resolveBinding(...)` to get the test methods: https://github.com/microsoft/vscode-java-test/pull/1042
- Introduce more lazy-load mechanisms: https://github.com/microsoft/vscode-java-test/pull/1044
- Get ASTNode from cache: https://github.com/microsoft/vscode-java-test/pull/1052
- Add cancellation checks: https://github.com/microsoft/vscode-java-test/pull/1061, https://github.com/microsoft/vscode-java-test/pull/1057
- Ask VS Code to introduce adaptive debounce to Code Lens providers: https://github.com/microsoft/vscode/issues/106267
- Not showing test explorer for non-java workspace: https://github.com/microsoft/vscode-java-test/pull/1110

Actually, other Java extensions as well as the JDT.LS itself also did a lot of works to improve the performance, which I'm not going to list all of them here. Anyway, good news are:

- After we started these works in 2020 Aug, there are much less complains for that, from the origin issue, you can see except for the last comment, other comments are all before 2020 Jul.
- Customers' feedback saying that the performance has a large improvement: https://github.com/microsoft/vscode-java-test/issues/832#issuecomment-679233411, some others come from online customer interview.

I'm not saying that the current status is perfect. we still have large space for improvement, but at least it's not that bad. Regarding to the comment: https://github.com/redhat-developer/vscode-java/issues/851#issuecomment-596522231, you can see that it takes a long time before the Java Language Server is ready. Given that the test runner has a [hard dependency](https://github.com/microsoft/vscode-java-test/blob/master/package.json#L459) on Java Language Server, it will not get activated until the Java Language Server is ready. In other words, it has no chance to make impact on performance during the import stage.

I think given the current information, there's no evidence showing that this extension has a great impact on the performance side. More information/investigation is needed.

**Comment by apupier** [comment]
sounds like there are great improvements already. i tested the use case in this comment https://github.com/redhat-developer/vscode-java/issues/851#issuecomment-596522231

it took me 40 minutes with VS code java and VS Code java test activated.
I first built the project locally on command-mien to avoid impact of artefact download.

i was unable to take a Thread dump during the heavy load, jstack was just unresponsive and dump the thread only at the end when things slowed down.

next is to try without VS Code java test extension (when I or someone have time) to be able to compare the impact of the extension

**Comment by jdneo** [comment]
I did this experiment today, and below are the details:

## Environment
### Machine
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports), 2.9 GHz Dual-Core Intel Core i5, 8 GB 2133 MHz LPDDR3

### OS
macOs Big Sur 11.2.3

### VS Code
Version: 1.55.0
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:05.981Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

### Repo
https://github.com/nuxeo/nuxeo, commit: 0fef68321525cb97a0da6079da394f0190698b0f

### Java Home
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

### JVM args
`-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx4G -Xms4G`
> I tried the default memory size(1G) and 2G, but both encountered out-of-memory exception, while 4G works fine

## Setup
### Initialize
1. First, open that project in VS Code, let the Java Langauge Server import all the projects
   > This is to make sure all the depednencies are downloaded to local .m2
2. Disable all the extensions exception for:
  - redhat.java
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-test

### Check time cost when test runner enabled
1. Trigger `Java: Clean Java Language Server Workspace` and select `restart and delete`
   > This is to remove all the caches generated by Java Language Server but preserve all the dependencies in the .m2
2. Observe the time cost to import the project. Here we observe the Java Language Server log file to check when all works are done. (when the thumb-up appears at the status bar and no more output generated in the log file.) Use the timestamp of the last trace to minus the start time will get the time cost.
   > Trigger `Java: Open Java Language Server Log File` to open that log file.

### Check time cost when test runner disabled
1. Disable the extensions `vscjava.vscode-java-test`
2. Trigger `Java: Clean Java Language Server Workspace` and select `restart and delete`
3. Use the same approach to get the time cost to import

## Result
### Test Runner enabled
| Start | End  | Total |
| --- |:---:| ---:|
| 15:22:04.354      | 16:05:53.940 | ~ 43min|

### Test Runner disabled
| Start        | End           | Total  |
| ------------- |:-------------:| -----:|
| 16:07:50.088      | 16:53:16.943 | ~ 46min|

There are no significant difference in two scenarios.

## Explanation
In VS Code, if extension `A`(here is test runner) depends on extension `B`(here is Java Language Server), VS Code's extension activation mechanism guarantees that `A` will not get activated until `B` is activated. The `redhat.java` will not signal activation finishing event until project import are finished. So basically, test runner has no chance to impact on the performance in the import stage.

**Comment by apupier** [comment]
@jdneo thanks for the manual. It sounds like there is no problem coming from vscode-java-test anymore with the provided steps.
