### ISSUE TITLE
Code Lens not showing "Run Test | Debug Test" since version v0.31.0 under @Test for Junit.

### ISSUE THREAD

**Issue by waimingkwok** [microsoft/vscode-java-test#1290]
It works again when downgraded to v0.30.1.

**Comment by jdneo** [comment]
Because we migrated to the new VS Code testing API. Please make sure you are using the latest VS Code. And then you can find a `decoration` at the left side of the editor: 

![Untitled](https://user-images.githubusercontent.com/6193897/130345451-4ede26b7-6271-46d8-9f2a-b1caa9f76acc.png)

_// Feel free to let me know if it's still not working._

**Comment by waimingkwok** [comment]
> Because we migrated to the new VS Code testing API. Please make sure you are using the latest VS Code. And then you can find a `decoration` at the left side of the editor:
> 
> ![Untitled](https://user-images.githubusercontent.com/6193897/130345451-4ede26b7-6271-46d8-9f2a-b1caa9f76acc.png)
> 
> _// Feel free to let me know if it's still not working._

Thanks for your quick response! It works according to what you have suggested.
