### ISSUE TITLE
Test output diff not showing blank lines

### ISSUE THREAD

**Issue by jdglaser** [microsoft/vscode-java-test#1441]
I've noticed that the "ExpectedOutput" vs "ActualOutput" view from tests ignores blank lines on strings. This makes debugging tests that compare strings really difficult as the expected and actual outputs appear to be the same.

![image](https://user-images.githubusercontent.com/32422167/175955667-bb6ffb93-113a-4c6e-9ca0-842fede493e9.png)

![image](https://user-images.githubusercontent.com/32422167/175956036-7312fb80-3d21-4d7d-a1df-deaace69382e.png)

I made sure that the below setting is set in my settings.json, but still no luck.

```json
    "diffEditor.ignoreTrimWhitespace": false,
```

Any help would be greatly appreciated.

Thanks!

**Comment by jdneo** [comment]
Thank you for reporting the issue!

This is a bug which caused by this line: https://github.com/microsoft/vscode-java-test/blob/7cbc39ea7a94eac5bded9af70d62cb8bce4ff097/src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts#L48

We simply split the runner's output and the empty line is ignored. I'll plan this bug fixing in our July milestone.

**Comment by jdneo** [comment]
@jdglaser, the fix should be contained in the pre-release version `0.35.2022063002` or higher. You can verify if it solves your problem if you want by switching to pre-release channel.
![image](https://user-images.githubusercontent.com/6193897/176606670-12fb02df-2757-4cfe-bd1c-5f26eb5ae9c8.png)
