### ISSUE TITLE
Update broke the extension

### ISSUE THREAD

**Issue by JoJoDeveloping** [microsoft/vscode-java-test#1442]
After updating to the latest version (0.35.2022062402), tests are no longer detected.

I'm not quite sure why, nor how I would debug this. Does anyone have suggestions on how to do so? Where are the log files?

**Comment by meledin** [comment]
You can find it under "Output -> Language Support for Java"

The plugin seems to be attempting to load a number of files that are not present, e.g.

```
Contains: Cannot extract bundle symbolicName or version /workspace/.vscode-remote/extensions/vscjava.vscode-java-test-0.35.1/server/com.microsoft.java.test.plugin-0.35.1.jar
java.nio.file.NoSuchFileException: /workspace/.vscode-remote/extensions/vscjava.vscode-java-test-0.35.1/server/com.microsoft.java.test.plugin-0.35.1.jar
...
Contains: Cannot extract bundle symbolicName or version /workspace/.vscode-remote/extensions/vscjava.vscode-java-test-0.35.1/server/org.eclipse.jdt.junit4.runtime_1.1.1200.v20200214-0716.jar
java.nio.file.NoSuchFileException: /workspace/.vscode-remote/extensions/vscjava.vscode-java-test-0.35.1/server/org.eclipse.jdt.junit4.runtime_1.1.1200.v20200214-0716.jar
...
Contains: Cannot extract bundle symbolicName or version /workspace/.vscode-remote/extensions/vscjava.vscode-java-test-0.35.1/server/org.eclipse.jdt.junit5.runtime_1.0.900.v20200513-0617.jar
java.nio.file.NoSuchFileException: /workspace/.vscode-remote/extensions/vscjava.vscode-java-test-0.35.1/server/org.eclipse.jdt.junit5.runtime_1.0.900.v20200513-0617.jar
```

Notably this happens from within GitPod for me (which is OpenVSX so YMMV). Using VSCode for Mac, I do not have any such issue (and those jar files are nowhere to be seen on the mac)

**Comment by jdneo** [comment]
@JoJoDeveloping Is your case the same as @meledin's?

**Comment by jdneo** [comment]
BTW, what's the version of `vscode-java` installed on your machine?

**Comment by meledin** [comment]
@jdneo if you're asking me, this issue is reproducible for me when running in GitPod workspaces only. Here's two GitPod workspaces that exemplify the issue. Please wait until all extensions have installed and then reload the gitpod window. You should see this message from the language support extension:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/821750/176962253-6f8a8022-8188-43f8-9e87-e267a3c5d4b9.png">

You can see the installed plugin versions in the `.gitpod.yml` file.

# Working copy (0.35.0)
https://gitpod.io/#https://github.com/meledin/vscode-java/tree/working

In this first env, the unit test is working, and we can run everything from the test panel.
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/821750/176962478-15bb5db2-3b85-4838-a2bc-c6a1991fc9ba.png">

# Broken copy (0.35.1)
https://gitpod.io/#https://github.com/meledin/vscode-java/

In this second environment, the [only difference](https://github.com/meledin/vscode-java/pull/1/files) is the installed version of `vscode-java-test` being 0.35.1 on `main` and 0.35.0 on the `working` branch. However, with that, we see these stack traces under the Output window.

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/821750/176962665-0e577925-77f0-4f34-907d-2ec3548610d8.png">

# Additional notes
I'm running VSCode on MacOS, but the gitpod containers are of course running under Linux, if that makes a difference to the plugin.

**Comment by s0nny7** [comment]
This happens on linux too, the extension tries to load jars from non-existing "[extension-dir]/server" folder, rolling back to 0.35.0 fixes the problem.

my setup:
archlinux
openjdk: 18.0.1.1
vs-code: 1.68.1-1
vscode-java: 1.8.0
vscode-java-test: 0.35.1

**Comment by jdneo** [comment]
@meledin, From the screenshot looks like not only the test runner extension, but the maven extension failed to activate due to the same error either. I'll use VS Code remote to take a look at this.

**Comment by jdneo** [comment]
@s0nny7 Could you share the way how do you download the test runner extension?

**Comment by jdneo** [comment]
@meledin The Open VSX team says that the issue has been fixed. Hope your problem can be resolved now.

**Comment by agarman** [comment]
I ran into this issue. Work around:

1. Downgrade to 0.35.0
2. Confirm tests are detected and loaded
3. Upgrade to 0.35.1
4. Confirm tests are now detected and loaded.

**Comment by jdneo** [comment]
@agarman, could you let me know how did you install the extension? Do you use it in official VS Code desktop? And what's your operation system?

**Comment by jdneo** [comment]
The OpenVSX team has fixed the broken extensions. If you encountered this issue when installing the extension from OpenVSX, please refer to the workaround provided by @agarman ❤️ 

Meanwhile, I cannot reproduce this issue in official VS Code desktop with test runner@0.35.1.

I guess this issue can be closed now.
