### ISSUE TITLE
VS Java Test extension is unable to detect JUnit tests

### ISSUE THREAD

**Issue by nilsreichardt** [microsoft/vscode-java-test#1498]
## Description

I have problems to run my tests in VS Code.

You can see on the left side that VS Code say that I have 0 tests. When I press the run button, nothing happens. Additionally, in the test lab, VS Code does not show the "Enable Java Tests" buttons.

How it should look:

<img width="525" alt="image" src="https://user-images.githubusercontent.com/24459435/197838901-8accd8cc-d64c-459b-83cb-854735a8642f.png">

I looks for me:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/24459435/197839166-21d85496-0929-412b-8cdd-49f85bd55dd4.png">

### Video

https://user-images.githubusercontent.com/24459435/197838497-9cae21b3-041f-48d3-9a45-b8367fd3a95d.mov

### Steps

* MacBook M1 Pro
* Version of Extension Pack for Java: v0.25.3

```
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```

**Comment by jdneo** [comment]
Is it possible to share a sample project for this issue?

**Comment by nilsreichardt** [comment]
Thanks for the quick reply 👍 

You can find under the following link two projects:
* `with-tests`: The project with tests (testing labs detects that this project has tests but says that this project has 0 tests, see video)
* `without-tests`: The project without tests (testing labs does not show the button "Enable Java Tests"

Link: https://github.com/nilsreichardt/playground/tree/java-testing-problems

However, I think this is not a problem with project and more a problem with some local configurations 🤔

**Comment by jdneo** [comment]
Ok, some explanation about the problems:

#### with-tests: The project with tests (testing labs detects that this project has tests but says that this project has 0 tests, see video)

This is because the extension will only display the tests in the folder which is defined as test source set. In this project, the test source set is defined as empty. So, no tests are displayed in the explorer. What you need to do is changing your `build.gradle` to:
```groovy
test {
    java {
        srcDirs 'src'   // <---- change here
    }
}
```
Then everything will work.
![image](https://user-images.githubusercontent.com/6193897/198174177-cddffc0c-50f9-44f5-9f72-1e760f3877f9.png)

------

#### without-tests: The project without tests (testing labs does not show the button "Enable Java Tests"

Currently, the `enable test` feature is only available to the project without build tools. Because for that kind of projects, users need to manually download the jars for the test framework and its transitive dependencies. This is complex, so we provide that feature helping users to setup the testing things with a few clicks. When it comes to build tool projects (Maven, Gradle), it's much easier since you just need to declare the test dependencies in the configuration files.

**Comment by nilsreichardt** [comment]
Oh, that’s work. Thanks for the awesome support! 🙏

I just read the [Java Testing in Visual Studio Code](https://code.visualstudio.com/docs/java/java-testing) documentation. They say something about the `implementation 'org.junit.jupiter:junit-jupiter:5.7.0'` but not about to make sure that `srcDirs` is set correct. Is this something that should be added to the docs?

Since the issue is resolved, I'm going to close the ticket 👍

**Comment by jdneo** [comment]
Oh, yes. We put that in the GitHub [wiki](https://github.com/microsoft/vscode-java-test/wiki/FAQ) but not mentioning that in the document. Thanks for pointing out.
