### ISSUE TITLE
Bug: duplicate test name is not handled

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode-java-test#1517]
duplicate test names are not shown differently in test navigator. 

```

static Stream<Arguments> f(){
  return null;
}

@ParameterizedTest
@MethodSource("f")
void foo(int a){
  fail();
}

@Test
void foo(){
  // Pass
}
```

**Comment by jdneo** [comment]
Root cause: the overload methods does not take into consideration when construct the item id: https://github.com/microsoft/vscode-java-test/blob/main/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/JavaTestItem.java#L58

Current implementation only picks the method name.

We can change the id schema to make it be able to distinguish overload methods. At the meantime, we need to check if the change has any impact on the runner output analyzer.

**Comment by Kropie** [comment]
I'll take a look into this @jdneo
