### ISSUE TITLE
vscode can't resolve launch configuration when running junit tests on java project (unmanaged)

### ISSUE THREAD

**Issue by ray-bao-mcgill** [microsoft/vscode-java-test#1525]
<img width="1512" alt="Screen Shot 2023-01-30 at 6 10 36 PM" src="https://user-images.githubusercontent.com/113869692/215617382-633345f4-8583-4e22-b749-ff9b0c80b157.png">

vscode version 1.74
<img width="541" alt="Screen Shot 2023-01-30 at 6 13 19 PM" src="https://user-images.githubusercontent.com/113869692/215617776-347f4a4b-b4bb-4941-9730-d5e5b41133c8.png">
<img width="220" alt="Screen Shot 2023-01-30 at 6 13 34 PM" src="https://user-images.githubusercontent.com/113869692/215617817-19faa0a5-396c-4285-8060-5f40aef00a44.png">

**Comment by jdneo** [comment]
Can you share a sample project for this issue?

**Comment by ray-bao-mcgill** [comment]
[sample.zip](https://github.com/microsoft/vscode-java-test/files/10541762/sample.zip)

**Comment by ray-bao-mcgill** [comment]
the peculiar part is that it was working a few hours ago, and then without changing anything, it stopped working

**Comment by jdneo** [comment]
Ok, it's because the secondary classes are not supported now, see: https://github.com/microsoft/vscode-java-test/issues/859.

As a workaround, you can rename your file to `AirportTest.java` and make the class `public`, for example:

![image](https://user-images.githubusercontent.com/6193897/215647989-12fceccb-9ff3-4f7d-b1be-b9a0259eda49.png)

**Comment by ray-bao-mcgill** [comment]
I see i see, thank you for the help!
