### ISSUE TITLE
junit 5 can't load tests if "maven.test.skip" set true

### ISSUE THREAD

**Issue by visla-perlin** [microsoft/vscode-java-test#1551]
I have a maven project,and "maven.test.skip" set true
`<maven.test.skip>false</maven.test.skip>`

then i can't see any test in test panel
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/115332532/226380206-9a91c429-6fae-42ac-b9de-ebb5f4a7bde8.png">

if  "maven.test.skip" set false,these tests can be list
<img width="992" alt="image" src="https://user-images.githubusercontent.com/115332532/226380586-a1229790-78f4-4598-99d5-db493124cb96.png">

I don't know why these tests are displayed based on maven configuration values,I just want to show these tests and I can run them manually.

or  I configured something wrong?

**Comment by jdneo** [comment]
I tried it locally but could not reproduce your issue:

![image](https://user-images.githubusercontent.com/6193897/226503088-107968b5-af8d-4e97-a37d-62dc7c54b568.png)

Is it possible to share a sample project?

**Comment by visla-perlin** [comment]
Thanks for you reply, and this is the sample project
https://github.com/visla-perlin/demo-test

**Comment by jdneo** [comment]
My bad, the spring-petclinic project I mentioned above was imported via Gradle before, so it was not impacted when I updated the pom.xml.

After I reimported via Maven, I can reproduce this it.

The root cause is that when setting `<maven.test.skip>true</maven.test.skip>`, the test source paths will be removed from the project source path, then they are not listed in the testing panel.

There is no configurations about this behavior for now, the extension will just follow the source paths provided from the build tool. But as a workaround, you can remove the `<maven.test.skip>true</maven.test.skip>` in the pom.xml. And when building your project from command line, append `-DskipTests` to skip the tests.

**Comment by visla-perlin** [comment]
It seems that this configuration cannot be ignored or overridden. In this case, I need to switch this value when publishing and developing,  Thanks.
