### ISSUE TITLE
sourcePaths in "java.test.config" not working

### ISSUE THREAD

**Issue by lucianthorr** [microsoft/vscode-java-test#1552]
I have a project using junit5 with a structure like
```
src/main/java - application code
src/test/java - unit tests
```

If I include the `src/test/java` as a sourcePath in the main project's `java.project.sourcePaths`, then the VSCode Testing panel correctly shows all the tests.

If I try to move `src/test/java` into the `java.test.config` sourcePaths and remove it from `java.project.sourcePaths`, then the VSCode Testing panel cannot find any of my tests.

I'm relatively new to how Java expects projects to be laid out but it seems to me that code in the test/ folder should not be included in the general application's source path.  Am I misunderstanding?  Thanks.

**Comment by jdneo** [comment]
I suppose you are working on a project without any build tools.

In this case, `java.project.sourcePaths` is the setting defines your project structure.

The `sourcePaths` in `java.test.config` is used to let debugger find the source jars of the dependencies, it's not about your project strucutre. So `java.project.sourcePaths` is the one you should use.

> it seems to me that code in the test/ folder should not be included in the general application's source path.
It's ok to include test code in the app's source path. Generally, just do include the tests when you export your application to jar files. Because tests are not needed at runtime usually.

**Comment by lucianthorr** [comment]
@jdneo Thanks and yes, you are correct, I'm not a build tool.
