### ISSUE TITLE
'Loading Test...' is blocking users from debugging

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-test#163]
Copied from Gitter:

Aleksei Gurianov @Guria Apr 10 20:12
Hi. I installed Java Extension Pack with vscode-java-debug. I have set up config to attach my local tomcat and it works. But the problem is that when I am trying to start Debug session for the first time since project opened I have a very long (decades of minutes) waiting period with "Loading tests..." in status bar. Can I avoid this somehow?

Manas Talukdar @manastalukdar Apr 12 09:42
Hi, it appears in one of the recent updates, every time I hit debug a full compilation is initiated, which takes time and slows down my development workflow. Previously the debugger would start very quickly, possibly because it did an incremental compilation, perhaps only if any changes were detected. Any way I can revert back to the old behavior?

**Comment by ansyral** [comment]
I did a test to add a timeout in test runner's `activate` function, and it turns out that runner isn't up you can still trigger debugging. So I suppose vscode wouldn't block other extension's operation till all extensions to load. One suspect is that full compilation leads to debugger to take a long time to respond.

**Comment by ansyral** [comment]
test runner itself wouldn't block user from debugging.

**Comment by jdneo** [comment]
Closing...

Let's see if the problem can be solved with lazy-load.

If anyone encountered this problem again, Feel free to reopen it.
