### ISSUE TITLE
"vmArgs": ["-Dfile.encoding=iso885915"] seems to be overided by something else in the java.test.config config

### ISSUE THREAD

**Issue by guillaumeagsp** [microsoft/vscode-java-test#1641]
Hello

when I put some specific args in the java.test.config, they are passed to code under test, except file.encoding, which is always stuck to UTF-8

```
"java.test.config": {
        "name": "MonConfig",

        "vmArgs": [
            "-Dfile.encoding=iso8859-15",
            "-DTITI=iso8859-15",
        ],
}
```

==>
```
mainid 2023-12-15 16:27:38,655 - INFO  ApplicationProperties - file.encoding = UTF-8
mainid 2023-12-15 16:27:38,657 - INFO  ApplicationProperties - TITI = iso8859-15
```

It seems that something is overiding this setting

The project is build by gradle. My build.gradle contains something like this :

```
   tasks.withType(Test) {
        // Configuration spécifique pour toutes les tâches de test des sous-projets
        systemProperty 'file.encoding', 'iso8859-15'
   }
```
and it work well when i use directly gradle in my vs console
```
    Test workerid 2023-12-15 16:52:15,934 - INFO  ApplicationProperties - file.encoding = iso8859-15
```

**Comment by jdneo** [comment]
Found the related code is here: https://github.com/microsoft/vscode-java-debug/blob/792249434fa8265a2b40d08956cc1b9dbe46e474/src/configurationProvider.ts#L362-L363.

**Comment by starball5** [comment]
Related on Stack Overflow: [Vscode / Java Extension / Test Panel : How to specify runtime file.encoding](https://stackoverflow.com/q/77667178/11107541)

Potentially related: #896 and https://github.com/microsoft/vscode-java-test/pull/885, https://github.com/Microsoft/vscode-java-test/pull/662

**Comment by guillaumeagsp** [comment]
OK, thank you for your answer. I dump here versions of vscode + extension. It could help

```
alexcvzz.vscode-sqlite@0.14.1
batisteo.vscode-django@1.14.0
donjayamanne.python-environment-manager@1.2.4
donjayamanne.python-extension-pack@1.7.0
GitHub.copilot@1.143.0
GitHub.copilot-chat@0.11.1
GitHub.vscode-pull-request-github@0.78.1
hediet.vscode-drawio@1.6.6
johnstoncode.svn-scm@2.17.0
mrorz.language-gettext@0.2.2
MS-CEINTL.vscode-language-pack-fr@1.85.2023121309        
ms-python.autopep8@2023.8.0
ms-python.black-formatter@2023.6.0
ms-python.python@2023.22.1
ms-python.vscode-pylance@2023.12.1
ms-toolsai.jupyter@2023.11.1003402403
ms-toolsai.jupyter-keymap@1.1.2
ms-toolsai.jupyter-renderers@1.0.17
ms-toolsai.vscode-jupyter-cell-tags@0.1.8
ms-toolsai.vscode-jupyter-slideshow@0.1.5
redhat.java@1.25.1
redhat.vscode-xml@0.26.1
tomoki1207.pdf@1.2.2
VisualStudioExptTeam.intellicode-api-usage-examples@0.2.8
VisualStudioExptTeam.vscodeintellicode@1.2.30
vscjava.vscode-gradle@3.13.5
vscjava.vscode-java-debug@0.55.0
vscjava.vscode-java-dependency@0.23.3
vscjava.vscode-java-pack@0.25.15
vscjava.vscode-java-test@0.40.1
vscjava.vscode-maven@0.43.0
wholroyd.jinja@0.0.8
ZainChen.json@2.0.2
```

**Comment by awilkins** [comment]
Hello!

I think the issue here is that `configurationProvider.ts` takes `encoding` straight from the `encoding` property of the launch config, and this is set before the `vmArgs` - it doesn't matter what you pass for `vmArgs` because the encoding is set afterwards by the launch constructor, and in most JVM implementations, last arg wins.

```/usr/lib/jvm/java-17-amazon-corretto/bin/java -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=localhost:46017,server=n,suspend=y -ea -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8```

The next part of the issue ... the `IExecutionConfig` used by the test plugins doesn't have an `encoding` slot (just `vmArgs`). You could argue this is by design because UTF-8 works pretty well for the majority of cases ... but you could also argue that if you need to change it, you need to change it.

I have integration tests that won't run because the client library I'm integrating passes the default VM charset as an argument to the server ... and the server can't cope with multi byte code pages, so it rejects the request. There's no way to change the client library (proprietary and complex and no alternative), so the only way the code works is if you set the JVM encoding to a single byte codepage.

The test plugin always forces `internalConsole` and has no slot to define `encoding` so it will always use `UTF-8`.

Perhaps this should get fixed by adding an encoding member to `java.test.config` and passing it to launch configs generated by the test plugin.

The workaround for this may be to roll your own launch configs for tests and include the `encoding` parameter, but this may not work in all circumstances.

**Comment by jdneo** [comment]
@awilkins  would you like to make a contribution? I think add `encoding` to `IExecutionConfig` is a low hanging solution.

**Comment by awilkins** [comment]
Had to change tthe p2 URL in `com.microsoft.java.test.tp.target` to get the java parts to build, but should be able to make progress on this ...
