### ISSUE TITLE
No test found to run when run test  test project color-checker.

### ISSUE THREAD

**Issue by sallyur** [Microsoft/vscode-java-test#3]
Environment

- Operating System: mac
- JDK version: 1.18.0_144
- Visual Studio Code version: 1.18.1
- Java test extension version: build25

Current result:
![image](https://user-images.githubusercontent.com/28860891/33360353-540f4120-d50e-11e7-8ad8-77a21f2680fc.png)

**Comment by stnguyen90** [comment]
+1 I'm also having this issue.

**Comment by bsaby** [comment]
Project: https://github.com/vscjavaci/java-test-ci/tree/master/color-checker
Build: 338

Result:
Open this project in vscode, test explorer can't load any tests, and there is no clodelens in the test file.
For this type project, expected behavior?
![image](https://user-images.githubusercontent.com/22470312/48329850-6f786480-e685-11e8-96f0-5e75f3b144ec.png)

**Comment by jdneo** [comment]
Dup with #470
