### ISSUE TITLE
VS Code reports test status incorrectly when classname ends with IT

### ISSUE THREAD

**Issue by boyarsky** [microsoft/vscode-java-test#381]
When using Maven, it is common to use *IT.java as the test class name to show it is an integration test. (vs an unit test). The [failsafe plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html) recommends this convention.

I wrote a very simple JUnit 5 integration tests class with one passing test and one failing test. In the Java editor, VS Code correctly shows a green check for the "good" test and a red check for the "bad" test. However, it shows both tests as skipped in the test reports list. It also shows zero tests as run on the bottom of the screen.
![junit5-it](https://user-images.githubusercontent.com/416926/47967065-98ff1380-e027-11e8-9212-b6b3bb54b549.jpg)

VS Code does behave properly if I rename my test from JeanneIT to JeanneTest. The test results and bottom bar both acknowledge the tests were run.
![junit5-test](https://user-images.githubusercontent.com/416926/47967064-956b8c80-e027-11e8-9553-86e621ec6881.jpg)

**Comment by boyarsky** [comment]
Note. When I saw another issue (#344) had a problem with the Maven plugin, I tried disabling that plugin. It solved #344 but not this one (#381). Mentioning so nobody wastes time going down that alley.

**Comment by jdneo** [comment]
Hi @boyarsky, is the problem still occur by using the newest version of Test Runner?

If yes, would you mind to provide a sample project with us to repro the issue?

**Comment by boyarsky** [comment]
It actually got worse. Now when I click "run test" on JeanneIT, it doesn't show anything in the report or the bottom bar.

Here's a project with just the two classes in it. JeanneTest behaves as expected. JeanneIT does not. Other than the name, the files are the same.
https://github.com/boyarsky/vs-code-test-runner-issue-381

**Comment by jdneo** [comment]
### Root Cause

We are using Junit 5's junit-platform-console to launch the test execution. The CLI has an option to restrict the class name, 
> the default pattern only includes class names that begin with "Test" or end with "Test" or "Tests".

see here: https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/options/AvailableOptions.java#L172-L177

### Workaround

You can change the default value by setting a workspace setting for `java.test.config`

```jsonc
{
    "java.test.config": {
        "args": ["--include-classname", ".*"]
    }
}
```

Open the `Setting` page and click `Edit in settings.json`

![image](https://user-images.githubusercontent.com/6193897/59575208-fd6d6f80-90ec-11e9-9d9d-d87a4d59dd76.png)


### Follow-up
I'll consider whether to set the value of `--include-classname` to `.*` by default.
