### ISSUE TITLE
There are some performance issues with loading large maven projects

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#461]
Build: 0.11.1
The project used: https://github.com/checkstyle/checkstyle

The test explorer has been loading method for more than an hour and still has not succeeded
![image](https://user-images.githubusercontent.com/22470312/49065169-2cf38200-f258-11e8-98aa-99c8a8da3add.png)

**Comment by RuiffCardoso** [comment]
I get the same issue with a large multi module project. Sometimes it just hangs and I need to restart vscode. 

Not sure if only related with vscode-java-test but it definitely slows down and I've been thinking on disable it when not testing because of the performance and startup times downgrade it causes.

The thing is that eclipse isn't much better so I don't care that much

**Comment by jdneo** [comment]
## Root cause
The extension will create a file watcher listening to the changes of all the java files.

During the project building, the LS might create/delete java files in the target folder, then the file watcher will keep triggering the explorer to refresh.

## Solution
Add a `testPathProvider`, when the file watcher receives the event, check the changed file is in the test path or not.

This component can also be used when provide the Code Lenses
