### ISSUE TITLE
Todo project: skip testEqualsObjects method 

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#488]
Build: 359
Project: https://github.com/Microsoft/todo-app-java-on-azure

Run from workspace root/workspace folder, the testEqualsObject method will be skipped.
![image](https://user-images.githubusercontent.com/22470312/49362588-1fd40880-f71a-11e8-9568-51b6fc3fcb33.png)
Test output:
![image](https://user-images.githubusercontent.com/22470312/49362602-25315300-f71a-11e8-88fe-c4fa14172219.png)

**Comment by jdneo** [comment]
## Root cause
The code logic [here](https://github.com/Microsoft/vscode-java-test/blob/master/java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/junit4/JUnit4RunnerUtil.java#L36) is wrong:

```java
public static List<JUnit4TestReference> createTestReferences(String[] suites) {
    if (suites.length == 0) {
        return emptyList();
    } else if (suites.length == 1) {
        final String suite = suites[0];
        final int separatorIndex = suite.indexOf('#');
        return separatorIndex == -1 ? getRequestForClass(suite) : getRequestForOneMethod(suite, separatorIndex);
    }
    return getRequestForClasses(suites);
}
```

We should determine the suite is a method or class by its full name, not the array length.

**Comment by jdneo** [comment]
@bsaby Fixed.
