### ISSUE TITLE
Java Test Explorer

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/vscode-java-test#552]
_From @thoni56 on December 31, 2018 9:55_

[Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) is a handy way to explore, run and visualize your tests directly from the test explorer.

I'm wishing for a Test Adapter for Junit et al. I'm really missing a red/green bar...

_Copied from original issue: Microsoft/vscode-java-pack#88_

**Comment by yaohaizh** [comment]
@jdneo

**Comment by jdneo** [comment]
Hi @thoni56

[Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) is an awesome extension, and I like the design of decoupling UI and data adapters.

For now my only concern is that the Test Explorer UI does not support lazy-loading the tree node, and this feature is not in their roadmap. (See: https://github.com/hbenl/vscode-test-explorer/issues/30)

Searching all the Java test packages/classes/methods in one call will take tens of seconds to several minutes, which depends on the user's project. So that's the reason we lazy-load the Java test explorer to avoid the activation taking too much time.

It seems that we still have a long way to go to integrate the Java Test Runner with the Test Explorer UI. But don't worry, we will try our best to improve the experience of Java Test Runner.

Thank you for the suggestions!
