### ISSUE TITLE
The test cases will run multiple times.

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-java-test#641]
If the user triggers tests from the workspace level, and if the user has some classes annotated with `@Suite`, then some of the test cases will run multiple time.

**Comment by pyramid-johng** [comment]
i found that if i had my test suite in the "java.test.config" args array, i got the double-run behavior when selecting a specific test/class via the code lens links.  after i removed it from my `settings.json` that behavior went "back to normal".

however, in the test explorer, there is still this behavior, because the test runner runs the whole suite when it gets to that class.  for example if you select "Run Test" from the "root" node in the tree, it will duly execute all your tests, then when it hits the suite, it will inadvertently re-run all the test cases that the suite called out in its `@SuiteClasses` annotation.

i think the Test Explorer must somehow be much smarter about enumerating the tests.  in particular, it should only ever present classes with `@Test` annotations within it.  the projects we have are ant-based, so the test explorer displays all the classes without tests, along with all the classes that are tests too!
a less-complicated solution (and one that's test framework agnostic) would be to obey what is in the `.classpath` file if one exists, or allow a glob pattern to spell out where to look for tests in `settings.json`.

**Comment by jdneo** [comment]
Hi @pyramid-johng, 

Thank you for the feedback. Based on your comments, besides the `@TestSuite` issue, another request is to make the test explorer only show items which are really test related, right?

**Comment by pyramid-johng** [comment]
thanks for your reply.  your assessment is correct:  i think it would provide a less-confusing UX if the Test Explorer could confine its display of classes using one of the alternatives i described in my previous comment.

**Comment by jdneo** [comment]
Thanks @pyramid-johng. Just found that there is a new request of this #768. Let's track this issue there.

**Comment by pyramid-johng** [comment]
Awesome, tyvm for your attention!
