### ISSUE TITLE
Cannot run inner class if triggering test from @RunWith(Suite.class)

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-test#647]
### Code:
```
@RunWith(Suite.class)
@Suite.SuiteClasses({
    TodoItemTest.class, //test case 1
    TodoApplicationTest.class //test case 2
})
public class TestSuite {             
}
```
### How to repro
Trigger test from TestSuite in test explorer
![image](https://user-images.githubusercontent.com/22470312/53949658-7aa84200-4105-11e9-9039-943d51ab0c04.png)

### Result:
Unable to run inner class contained in TodoItemTest class, but if I trigger test from TodoItemTest calss level in test explorer, the inner class can be run.

**Comment by jdneo** [comment]
Hmm... This is by design.

But, if anyone thinks that this behavior is not right, please let us know or reopen this issue.

Thanks.

**Comment by steinerthomas** [comment]
I think it's right, that you can't run those inner class tests by design, if you have a test suite. 

But I would expect that the inner class tests are at least listed in the Testing View and that I can right click them and "Go to Test".

As it is now, the inner tests only get listed there after they were executed once and you can't right click and "Go to Test". It's only possible to hide a test.

Is this possible? Should I create an issue for that?

**Comment by jdneo** [comment]
@steinerthomas please go ahead. And it would be helpful if a sample project could be attached.
