### ISSUE TITLE
Jump between code and corresponding test case

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-java-test#660]
Can we have a feature to allow users to jump back and forth between the application code and the logic?

**Comment by jdneo** [comment]
Two features need to be implemented here:

1. test target -> test
2. test -> test target

**Comment by jdneo** [comment]
End game verification steps:

1. Open a Java project contains tests.
2. If the project structure follows `src/main/java` & `src/test/java`, commands can be found at the editor context menu. Otherwise, you can find them in the command palette.
3. `Go to Tests` will find all classes that contains the current type's name and display them in the reference view.
4. If only one result found, directly open that class
5. If no results found, user can choose `generate tests` or `search files`.
6. `Go to Test Subjects` will first remove all the `Test/Tests` in the type name and search types contains the replaced string.
7. If no results found, user can `search files`.
