### ISSUE TITLE
Disabled methods should not show status Code Lens

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#672]
Bits: 454
### Repro steps:

1. Open a Junit5 project
2. Run the disabled case

### Result:
![image](https://user-images.githubusercontent.com/22470312/55314520-e1b6dd80-549c-11e9-86c3-459ebda2a22f.png)

**Comment by jdneo** [comment]
_Comments from @katzelad in https://github.com/microsoft/vscode-java-test/issues/757:_

When manually executing (using CodeLens) a @Test method with @Ignore in IntelliJ the test is still executed, which is useful in order to run tests which should not be executed by the CI service.
With this extension, the test is ignored and nothing happens.
I think the test should still run, as this is the most intuitive behavior for the per-method CodeLens.
Thanks

**Comment by jdneo** [comment]
So we now have two choices here:

- Do not show CodeLens for Disabled/Ignored tests
- Show CodeLens for Disabled/Ignored tests and make them runnable.

**Comment by psybers** [comment]
Third option?

* Show CodeLens for Disabled/Ignored tests, but don't have it include the 'status' of the test unless that test was manually run (in other words the Lens would show `Run Test | Debug Test` only)

In other words, right now it shows `?` for status and that affects the overall class's test status as well.

The default behavior could be to ignore them when running all tests in the class and have the status act as if those tests don't exist. But still allow someone to manually run them (at which point it would start showing the status).

**Comment by jdneo** [comment]
@psybers yes, that sounds better!

**Comment by jdneo** [comment]
In 0.31.0, we support the newest VS Code testing API in 1.59.0.

There is no Code Lens anymore, instead you can see a editor decoration at the left side:
![image](https://user-images.githubusercontent.com/6193897/128447175-e722dc8e-9a53-4996-9abd-15e6dd16f4d1.png)
