### ISSUE TITLE
Cannot print the Chinese character correctly in JDK12 environment on Mac

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#710]
Project: https://github.com/bsaby/todo-app-java-on-azure/tree/testrunner

### Environment:

- OS: Mac
- JDK: 12
- Java Test Runner Extension: 0.17.0

### Repro steps:
1. Open the project in vscode
2. Change the `files.encoding `settings to gbk and make sure the encoding used by language server is gbk too.
3. Run encoding test method

### Result:
![image](https://user-images.githubusercontent.com/22470312/58161666-40d1eb00-7cb3-11e9-8bfe-757e33b1359a.png)

**Comment by jdneo** [comment]
I found that the same issue could not be repro on Windows, but can only repro on Mac with JDK12. Don't know who should be blamed. The `defaultCharset` will always be `UTF-8` even if I pass `-Dfile.encoding=gbk` into the JVM args. 🙀

Closing it for now since it seems not an issue of the extension. If anyone meets this problem, just feel free to comment and let us know.

Thanks,
