### ISSUE TITLE
The class which only contains nested classes can't show code lens

### ISSUE THREAD

**Issue by bsaby** [microsoft/vscode-java-test#720]
### Environment:
OS: Mac
JDK: 8
Java Test Runner Extension: 0.17.0
### Repro steps:
1. Git clone https://github.com/bsaby/junit5-samples/tree/testrunner/junit5-jupiter-starter-maven
2. Open the MyNestedTest  java file

### Result:
You will find that no code lens on the class MyNestedTest 
![image](https://user-images.githubusercontent.com/22470312/59022638-b8417600-8880-11e9-9dc7-bf7fa93cf89d.png)
But if I add a normal test method to this class, the code leans will appear
![image](https://user-images.githubusercontent.com/22470312/59022856-2ab25600-8881-11e9-8419-9d1238543b24.png)

**Comment by jdneo** [comment]
Just took a look about the IntelliJ's experience, though the first level class could be triggered directly, but it will show a message: `No tests were found`. (Because there is no test methods in that class, the @Nested class should not be taken into consideration)

![image](https://user-images.githubusercontent.com/6193897/70218203-851f6700-177d-11ea-9505-708a2b881545.png)

So in our implementation, not showing the Code Lens in this scenario is valid.

I'm closing it since there is nothing to fix.
