### ISSUE TITLE
Test Explorer should only show classes with tests

### ISSUE THREAD

**Issue by psybers** [microsoft/vscode-java-test#768]
This might be an artifact of my project using Ant, but right now the Test Explorer shows every class in my system - even ones that do not contain any tests at all.

FEATURE REQUEST: What would be preferred is if the explorer only lists classes containing at least 1 test and filters out the non-test classes.

**Comment by jdneo** [comment]
Thank you @psybers for the feedback.

A background of this is that, In order to get all the test packages/classes, the extension needs to search deeply to the method level to know that if the class is really test related. This might take a long time especially in large projects. So the current implementation is just kind of lazy-load.

But I agree with your that if the explorer can only show the test classes, it can improve the UX a lot. Let me think if there is any way to achieve that without hurting the performance.

**Comment by llgcode** [comment]
Thanks @jdneo,
I also have this problem in my project. Is there a workaround to this issue ?
I use junit4, and annotate my methods with @Test

**Comment by jdneo** [comment]
This should be addressed in 0.31.0. Those utility class will not show in the test explorer anymore

**Comment by psybers** [comment]
Thanks, I can confirm this works as expected in 0.31.0!

**Comment by ksuraj20** [comment]
Exception occured while running tests.
java.lang.RuntimeException: No test found to run.
	at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:29)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)

**Comment by jdneo** [comment]
@ksuraj20 Can you provide a sample project for the problem you met?
