### ISSUE TITLE
Cannot run meta annotation tests from test explorer

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-java-test#773]
**Environment:**
OS: Win10
JDK: 8/12
Java Test Runner Extension: 0.19.0

**Repro steps:**

1. Git clone https://github.com/bsaby/junit5-samples/tree/testrunner/junit5-jupiter-starter-maven
2. Run the MyFastTestIT java file

**Result:**
Cannot run meta annotation tests from test explorer, works from CodeLens.
![image](https://user-images.githubusercontent.com/41051257/62761094-4839b100-bab8-11e9-9cb7-00b4f1535fb7.png)

**Comment by jdneo** [comment]
Root cause: https://github.com/microsoft/vscode-java-test/blob/master/java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java#L185-L189

We are using the search engine to search all the test items but the search engine does not support search the annotation hierarchically. That's why meta annotations are not able to be found.
