### ISSUE TITLE
shortenCommandLine Setting

### ISSUE THREAD

**Issue by astrelsky** [microsoft/vscode-java-test#824]
I'm building a plugin for ghidra which I am looking to run tests on. The .classpath file I have has a huge number of entries so the test runner automatically shortens it and passes it as a jar file. Unfortunately ghidra needs to find its application.properties which it does by iterating over the classpath entries via `
String[] classpath = System.getProperty("java.class.path").split(File.pathSeparator);
`
It then proceeds to only sees the single jar file and is unable to locate the application.properties which causes my tests to instantly fail.

I'm able to debug my plugin because I have the debug launch setting set as
`"shortenCommandLine": "argfile"`
If I could set this for the test runner it would be appreciated.

**Comment by jdneo** [comment]
Hey @astrelsky,

Are you using JDK higher than 9? And what's the test framework you are using? Is it JUnit 4 or 5 or TestNG?

Thanks.

**Comment by astrelsky** [comment]
> Hey @astrelsky,
> 
> Are you using JDK higher than 9? And what's the test framework you are using? Is it JUnit 4 or 5 or TestNG?
> 
> Thanks.

I am using the latest JDK and using JUnit 4.

**Comment by jdneo** [comment]
@astrelsky Is the problem still occur if you are using the latest Test Runner extension?

**Comment by astrelsky** [comment]
> @astrelsky Does the problem still occur if you are using the latest Test Runner extension?

It seems to be working just fine now.

**Comment by jdneo** [comment]
@astrelsky It's because we just released a version around the day you filed this issue. The current marketplace version(0.20.0) will fully leverage the Java Debugger extension to launch the JUnit 4 tests, which means the launch behavior is controlled by the debugger.

In next release version, we will migrate the launching of JUnit 5 & TestNG to the Java Debugger as well. After that, users can control the launch behavior by just updating the related Debugger settings.

Anyway, thank you for your feedback. This let us know that the refactoring work we are doing recently provides some values to our users. :)
