### ISSUE TITLE
@BeforeAll on non-static method fails silently

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-test#935]
The following code prevents my tests from running and doesn't give me any clues that something is wrong.

```
@BeforeAll
void beforeAll() {
    //do some work here
}
```

needs to be `static void beforeAll()`!

**Comment by jdneo** [comment]
I think this issue has the same root cause with #931, which has been fixed in #932.

<img width="1271" alt="Screen Shot 2020-02-12 at 9 36 15 AM" src="https://user-images.githubusercontent.com/6193897/74295153-2678f980-4d7b-11ea-8e13-f71c5ac7f6d4.png">

The fix will be released in the next version. But before it releases, you can make your own build to work around for that.

Here are the steps:
1. clone this repo
2. `npm install`
3. `npm run build-plugin`
4. `npx vsce@latest package`

**Comment by spottedmahn** [comment]
>I think this issue has the same root cause with #931, which has been fixed in #932.

Oh, yeah, duh! 🤦‍♂️

![image](https://user-images.githubusercontent.com/14079228/74355468-eae62b80-4d8a-11ea-8d2e-324b1eaadd28.png)

Beautiful! 🎉
