### ISSUE TITLE
[Feature] Add new lines to the Java Test Report to separate "Cause by..." clauses

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode-java-test#959]
Currently, this is what I see when attempting to locate "Cause by" clauses in the Java Test Report:

![image](https://user-images.githubusercontent.com/6444116/76373358-8fba4100-6316-11ea-871b-f2ac721ae2b8.png)

The way it is displayed is because of the recent merged code changes here:

https://github.com/microsoft/vscode-java-test/pull/942

But I found out something I wanted to point out.

As shown in the red box, there is a lack of separation from the previous exception's stack traces to the next exception, labeled with a "Cause by..." text.

I would like to request to add a couple of new lines, about 2 or 3 of them, so the separation of the stack traces is more obvious and easier to notice, like so, using the same picture for reference:

![image](https://user-images.githubusercontent.com/6444116/76373538-022b2100-6317-11ea-86ac-c7478bf372c5.png)

**Comment by spottedmahn** [comment]
I like that 👍.  Make it easy to find it!

What about some emoji(s) too? 🚨

**Comment by jdneo** [comment]
I was trying to add some style to the `Caused by:` line, but failed to achieve that in pug. It will also escape the tag to plain text.

Below is the best I can do so far:
<img width="635" alt="Screen Shot 2020-03-20 at 10 40 13 PM" src="https://user-images.githubusercontent.com/6193897/77174392-f3edb980-6afb-11ea-92ac-32226423bb63.png">

But I still hope I can highlight the words `Caused by:` by another font-color. Does anyone know how to do that in pug? The related code line is: https://github.com/microsoft/vscode-java-test/blob/master/resources/templates/report_method_table.pug#L43

**Comment by jdneo** [comment]
Ok I know how to do it now, I think this is much better:
<img width="635" alt="Screen Shot 2020-03-21 at 10 12 51 AM" src="https://user-images.githubusercontent.com/6193897/77217327-99387a00-6b5c-11ea-813d-cac3f93bdac2.png">

**Comment by tommai78101** [comment]
Nice, emojis or highlights are both viable options to make the `Caused by` messages more apparent. Making them obvious is this issue's main user story.
